[tool.poetry]
name = "aws-container"
version = "0.1.0"
description = ""
authors = ["m4-sato <mssst1116@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9" # Lambdaランタイムに合わせて >=3.9, <3.10 などでも可
requests = "2.27.1"
beautifulsoup4 = "4.12.3"
python-dateutil = "2.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
